# Generated by Django 5.2.5 on 2025-10-01 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пример: Новости, ПДД', max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Автозаполняется. Используется в URL', max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article', 'Статья'), ('video', 'Видео')], default='article', help_text='Для совместимости с API v2', max_length=20, verbose_name='Тип категории')),
                ('name', models.CharField(help_text='Пример: Новости, Технологии', max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Автозаполняется. Используется в URL.', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Необязательно. Пояснение к категории.', verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, help_text='Оставьте пустым для корневой категории', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='news.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.TextField(blank=True, help_text='Появится в списке постов', verbose_name='Лид/описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title_picture', models.CharField(blank=True, help_text='MD5-хеш, 32 символа в нижнем регистре', max_length=200, verbose_name='S3 ключ (md5)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('youtube_url', models.URLField(blank=True, help_text='Ссылка на видео YouTube', verbose_name='YouTube ссылка')),
                ('rutube_url', models.URLField(blank=True, help_text='Ссылка на видео RuTube', verbose_name='Rutube ссылка')),
                ('vkvideo_url', models.URLField(blank=True, help_text='Ссылка на видео VK Видео ', verbose_name='VK Видео ссылка')),
                ('title', models.CharField(blank=True, help_text='Автозаполняется. Название видео, до 200 символов', max_length=200, verbose_name='Название')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Автозаполняется. Ссылка на обложку')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='news.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s', to='news.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткий заголовок статьи, до 200 символов', max_length=200, verbose_name='Заголовок')),
                ('lead', models.TextField(blank=True, help_text='Появится в списке постов', verbose_name='Лид/описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title_picture', models.CharField(blank=True, help_text='MD5-хеш, 32 символа в нижнем регистре', max_length=200, verbose_name='S3 ключ (md5)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('body', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('is_featured', models.BooleanField(default=False, help_text='Пост будет постоянно отображаться в верхней части главной страницы', verbose_name='Закрепить')),
                ('slug', models.SlugField(help_text='Автозаполняется. Используется в URL', max_length=200, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='news.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s', to='news.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Cтатья',
                'verbose_name_plural': 'Cтатьи',
                'indexes': [models.Index(fields=['is_featured', 'status'], name='news_post_is_feat_93699e_idx')],
            },
        ),
    ]
