# Generated by Django 5.2.7 on 2025-10-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("V", "Черновик"), ("A", "Опубликован")],
                default="A",
                help_text="Для совместимости с API v2",
                verbose_name="Тип категории",
            ),
        ),
    ]
