# Generated by Django 5.2.5 on 2025-10-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='title_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Автозаполняется. Ссылка на обложку'),
        ),
    ]
