# Generated by Django 5.2.5 on 2025-09-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_created_at_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_slug_per_parent',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='news_catego_slug_0c9c67_idx'),
        ),
    ]
