# Generated by Django 5.2.7 on 2025-10-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_category_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("V", "Видео"), ("A", "Статья")],
                default="A",
                help_text="Для совместимости с API v2",
                verbose_name="Тип категории",
            ),
        ),
    ]
