# Generated by Django 5.2.5 on 2025-10-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lead',
            field=models.TextField(blank=True, help_text='Описание поста', verbose_name='Лид/описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Краткий заголовок, до 200 символов', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lead',
            field=models.TextField(blank=True, help_text='Автозаполняется. Описание видео', verbose_name='Лид/описание'),
        ),
    ]
