# Generated by Django 5.2.5 on 2025-09-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Body (blocks)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
