# Generated by Django 5.2.5 on 2025-09-06 06:51

import django_editorjs.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_body_json_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_json',
            field=django_editorjs.fields.EditorJsField(blank=True, default='{}', verbose_name='Текст (JSON)'),
            preserve_default=False,
        ),
    ]
