# Generated by Django 5.2.5 on 2025-09-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_body_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_json',
            field=models.JSONField(default=list),
        ),
    ]
