# Generated by Django 5.2.5 on 2025-09-06 14:04

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_body_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_json',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, default=dict, verbose_name='Текст (JSON)'),
        ),
    ]
