# Generated by Django 5.2.5 on 2025-09-06 18:05

import django_editorjs.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_post_body_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_json',
            field=django_editorjs.fields.EditorJsField(blank=True, default=dict, verbose_name='Текст (JSON)'),
        ),
    ]
