# Generated by Django 5.2.5 on 2025-09-07 05:42

import django_editorjs2.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_post_body_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_json',
            field=django_editorjs2.fields.EditorJSField(blank=True, default=dict, verbose_name='Текст (JSON)'),
        ),
    ]
