# Generated by Django 5.2.5 on 2025-09-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_post_news_post_status_01ccc8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True, help_text='Ссылка на видео YouTube', verbose_name='YouTube ссылка')),
                ('rutube_url', models.URLField(blank=True, help_text='Ссылка на видео RuTube', verbose_name='Rutube ссылка')),
                ('vkvideo_url', models.URLField(blank=True, help_text='Ссылка на видео VK Видео ', verbose_name='VK Видео ссылка')),
                ('title', models.CharField(blank=True, help_text='Автозаполняется. Краткий заголовок статьи, до 200 символов', max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Автозаполняется. Используется в URL', max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Автозаполняется. Необязательно. Пояснение к категории.', verbose_name='Описание')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Автозаполняется. Ссылка на обложку')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, help_text='Видео будет постоянно отображаться в верхней части главной страницы', verbose_name='Закрепить на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Необязательно. Пояснение к категории.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Пример: Новости, Технологии', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для корневой категории', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='news.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Автозаполняется. Используется в URL.', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='alt',
            field=models.CharField(blank=True, help_text='Текст для атрибута alt', max_length=100, verbose_name='Описание (alt)'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(help_text='Изображение', upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='original_name',
            field=models.CharField(blank=True, help_text='Имя файла при загрузке', max_length=100, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст (plain)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Появится в списке постов', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Пост будет постоянно отображаться в верхней части главной страницы', verbose_name='Закрепить на главной'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Автозаполняется. Используется в URL', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Краткий заголовок статьи, до 200 символов', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Пример: Новости, ПДД', max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Автозаполняется. Используется в URL', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['uploaded_at'], name='news_mediaa_uploade_5d5b64_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at', 'status'], name='news_post_publish_b675be_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='news_tag_slug_4142b7_idx'),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='news.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='news.tag', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['slug'], name='news_video_slug_69934e_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['published_at'], name='news_video_publish_39e653_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='news_video_status_7f53e7_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category', 'status'], name='news_video_categor_a22795_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured', 'status'], name='news_video_is_feat_8c04b5_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-published_at', 'status'], name='news_video_publish_bba5ba_idx'),
        ),
    ]
