# Generated by Django 5.2.5 on 2025-09-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_video_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='news_catego_slug_0c9c67_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_slug_543168_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='news_tag_slug_4142b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='news_video_slug_69934e_idx',
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автозаполняется. Используется в URL', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
