# Generated by Django 5.2.5 on 2025-09-24 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_category_news_catego_slug_0c9c67_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_publish_4ef118_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_status_01ccc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_categor_da046a_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_is_feat_93699e_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_publish_b675be_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='news_video_publish_39e653_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='news_video_status_7f53e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='news_video_categor_a22795_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='news_video_is_feat_8c04b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='news_video_publish_bba5ba_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rutube_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vkvideo_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('article', 'Статья'), ('video', 'Видео')], default='article', help_text='Для совместимости с API v2', max_length=20, verbose_name='Тип категории'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='s3_key',
            field=models.CharField(blank=True, help_text='MD5-хеш, 32 символа. Автозаполняется при сохранении.', max_length=32, null=True, unique=True, verbose_name='S3 ключ (md5)'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Лид/описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_picture',
            field=models.CharField(blank=True, max_length=500, verbose_name='Главное изображение (URL)'),
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='video',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Лид/описание'),
        ),
        migrations.AddField(
            model_name='video',
            name='rutube_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='RuTube ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_picture',
            field=models.CharField(blank=True, max_length=500, verbose_name='Главное изображение (URL)'),
        ),
        migrations.AddField(
            model_name='video',
            name='vk_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='VK Video ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='YouTube ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Закрепить'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
