# Generated by Django 5.2.5 on 2025-09-25 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_post_options_alter_video_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Cтатья', 'verbose_name_plural': 'Cтатьи'},
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='file',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_extension',
            field=models.CharField(default='jpg', max_length=10, verbose_name='Расширение файла'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Оригинальное имя файла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем загружено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='s3_key',
            field=models.CharField(default=1, help_text='MD5-хеш, 32 символа в нижнем регистре', max_length=32, unique=True, verbose_name='S3 ключ (md5)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.mediaasset', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.mediaasset', verbose_name='Главное изображение'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', 'status'], name='news_post_is_feat_93699e_idx'),
        ),
    ]
