# Generated by Django 5.2.5 on 2025-09-25 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_post_options_remove_mediaasset_alt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rutube_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vk_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='video',
            name='rutube_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео RuTube', verbose_name='Rutube ссылка'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='news.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='Автозаполняется. Ссылка на обложку'),
        ),
        migrations.AddField(
            model_name='video',
            name='vkvideo_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео VK Видео ', verbose_name='VK Видео ссылка'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео YouTube', verbose_name='YouTube ссылка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Пост будет постоянно отображаться в верхней части главной страницы', verbose_name='Закрепить'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lead',
            field=models.TextField(blank=True, help_text='Появится в списке постов', verbose_name='Лид/описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Автозаполняется. Используется в URL', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='news.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Краткий заголовок статьи, до 200 символов', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_picture',
            field=models.CharField(blank=True, default=1, help_text='MD5-хеш, 32 символа в нижнем регистре', max_length=200, verbose_name='S3 ключ (md5)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lead',
            field=models.TextField(blank=True, help_text='Появится в списке постов', verbose_name='Лид/описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(help_text='Автозаполняется. Используется в URL', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, help_text='Автозаполняется. Название видео, до 200 символов', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_picture',
            field=models.CharField(blank=True, default=1, help_text='MD5-хеш, 32 символа в нижнем регистре', max_length=200, verbose_name='S3 ключ (md5)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
