# Generated by Django 5.2.5 on 2025-09-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_remove_video_description_remove_video_rutube_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_json',
        ),
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.DeleteModel(
            name='MediaAsset',
        ),
    ]
