name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv venv
          uv sync --all-extras

      - name: Setup environment variables
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-key-for-ci-$(openssl rand -hex 32)" >> $GITHUB_ENV
          echo "DEBUG=False" >> $GITHUB_ENV
          echo "AWS_S3_CUSTOM_DOMAIN=" >> $GITHUB_ENV
          echo "AWS_STORAGE_BUCKET_NAME=" >> $GITHUB_ENV
          echo "YOUTUBE_API_KEY=" >> $GITHUB_ENV

      - name: Run migrations
        run: |
          .venv/bin/python manage.py migrate

      - name: Run Django tests
        run: |
          .venv/bin/python manage.py test --verbosity=2

      - name: Run Django check
        run: |
          .venv/bin/python manage.py check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv venv
          uv sync --all-extras

      - name: Setup minimal environment for linting
        run: |
          echo "SECRET_KEY=test-key" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///:memory:" >> $GITHUB_ENV
          echo "AWS_S3_CUSTOM_DOMAIN=" >> $GITHUB_ENV
          echo "AWS_STORAGE_BUCKET_NAME=" >> $GITHUB_ENV

      - name: Run black code formatting check
        run: |
          .venv/bin/python -m black --check .

      - name: Run mypy type checking
        run: |
          .venv/bin/python -m mypy .
